// auth.router.js
const express = require('express')
const router = express.Router()
const login = require('./login')
const register = require('./register')
const logout = require('./logout')
const notes = require('./notes')
const verifyEmail = require('./verifyEmail')
const getNotesUser = require('./getNotesUser')
const delNoteUser = require('./delNote')
const cvdata = require('./cvdata')
const generatePdf = require('../service/generatePdf')
const getdatacv = require('./getdatacv')
const delSkill = require('./delSkillFromCv')
const { telegramBot } = require('../bot/telegramBot')
const getTalkBot = require('../bot/getTalkBot')
const postChatId = require('./postChatId')
const getChatId = require('./getChatId')


router
  .post('/login', login)
  .post('/signup', register)
  .post('/logout', logout)
  .post('/notes', notes)
  .post('/cvdata', cvdata)
  .post('/cvinfo', getdatacv)
  .post('/cvpdf', generatePdf)
  .post('/foobot', telegramBot)
  .post('/tg/send', getTalkBot)
  .post('/tg/chat', postChatId)
  .get('/tg/chat', getChatId)
  .get('/notes', getNotesUser)
  .get('/verify/:emailToken', verifyEmail)
  .delete('/notes/:id', delNoteUser)
  .delete('/cv/:cvId/skills/:skillId', delSkill)

module.exports = router
